### ISSUE TITLE
QueryParameter needs to append "In"

### ISSUE THREAD

**Issue by kabol** [pklauke/pycamunda#18]
https://github.com/pklauke/pycamunda/blob/44dba502d5afce2a2fc290745a4eb0ec9cb3a271/pycamunda/variable.py#L80

I was querying variables on my server and got OutOfMemory even though I was passing in a processInstanceId. Turns out there is a small bug in the naming. Should be a quick fix.

**Comment by pklauke** [comment]
The issue is now fixed in version v0.2.0.

Regards,
Peter

**Comment by kabol** [comment]
thanks for the quick turnaround!
