### ISSUE TITLE
Process instance variables subresource

### ISSUE THREAD

**Issue by milj** [pklauke/pycamunda#20]
Hello!

First of all I would like to thank you @pklauke for developing `pycamunda`. It seems to be the most complete Camunda REST API client out there.

I'm looking into ways to update process variables of a running process instance. The Camunda API documentation explains that there is a "Variables" subresource under "Process Instance":
https://docs.camunda.org/manual/7.15/reference/rest/process-instance/
https://docs.camunda.org/manual/7.15/reference/rest/process-instance/variables/

However, I cannot find any info how to access that "Variables" subresource in the `pycamunda` documentation:
https://pycamunda.readthedocs.io/en/latest/src/api/processinst.html

Am I looking in the wrong place or is this not implemented yet?

**Comment by kabol** [comment]
I think it's not implemented yet. See comment under GetList
`variables – # TODO (add via its own method?)`

**Comment by pklauke** [comment]
Hi!

Unfortunately, some parts of the Camunda REST api are not implemented in pycamunda yet. I have noted that the Variables subresource of ProcessInstance is needed and I'll add it as soon as possible!

> I think it's not implemented yet. See comment under GetList 
https://pycamunda.readthedocs.io/en/latest/src/api/processinst.html#getlist
> `variables – # TODO (add via its own method?)`

You're right, it's missing. The link you posted is a different part though. That one is for filtering process instances by variables when retrieving a list of them.

Regards,
Peter

**Comment by milj** [comment]
Thank you for the replies. I will probably need the variable updating functionality in the next few weeks. If so, I can spend some time helping with the implementation.

**Comment by pklauke** [comment]
With version v0.2.0 pycamunda does now support the variables subresource of process instance. The endpoints are accessible using the [pycamunda.processinst.Variables*](https://pycamunda.readthedocs.io/en/v0.2.0/src/api/processinst.html#variablesdelete) classes.

Regards,
Peter

**Comment by milj** [comment]
Thank you!
