### ISSUE TITLE
Migrate Extension to the Camunda Community Hub?

### ISSUE THREAD

**Issue by celanthe** [pklauke/pycamunda#22]
Hello!

I hope today finds you well! My name is Rin Oliver, and I'm a Technical Community Builder at Camunda. I'm opening this issue today to ask if you might be interested in migrating this extension over to the [Camunda Community Hub](https://github.com/Camunda-Community-Hub)?

We'd love to hear your feedback on how we might improve the overall community extension development process for maintainers and contributors moving forward, and learn more about what you'd like to see from this initiative in the future.

If migrating this extension something you'd be interested in, I can send you the instructions for doing so via email, or whatever communication method works best for you. I'm also more than happy to schedule a call and talk over this in more detail if that would be preferable to you, for whenever best suits your schedule over the next few weeks.

Thank you so much for your time. I look forward to hearing from you.

Best,
Rin

**Comment by pklauke** [comment]
Hi Rin,

thank you for suggestion, I appreciate that very much! However, currently I am very happy with the possibilities I have on my personal GitHub page. So I'm currently not interested in migrating the package.

Kind regards,
Peter
