### ISSUE TITLE
Current Camunda version (7.16) no longer has field 'errorDetails' in http://localhost:8080/engine-rest/external-task

### ISSUE THREAD

**Issue by Dutcho** [pklauke/pycamunda#35]
which makes line 55 of externaltask.py fail:
```
File "C:\...\pycamunda\externaltask.py", line 55, in load
    error_details=data['errorDetails'],
KeyError: 'errorDetails'
```

**Comment by pklauke** [comment]
Hi,

thanks for reporting this issue! With pycamunda v0.6.1 the `errorDetails` field is now optional and able to support both newer and older Camunda versions.

Kind regards,
Peter
